[config]

[config.palette]
theme = "dark"         # or "dark"
scheme = "default"     # palette variant
variation = "standard" # handpicked variation
contrast = 1.0         # contrast multiplier (adjust brightness/contrast)

[templates.wlogout]
input_path = '~/.config/matugen/templates/wlogout.css'
output_path = '~/.config/wlogout/colors.css'
