$background = rgb(1F1E25)
$foreground = rgb(FFF4FE)
$color0 = rgb(45444C)
$color1 = rgb(B0787D)
$color2 = rgb(759135)
$color3 = rgb(999335)
$color4 = rgb(BF8B93)
$color5 = rgb(B79D79)
$color6 = rgb(BFA7BD)
$color7 = rgb(F7E6F5)
$color8 = rgb(ADA1AC)
$color9 = rgb(EBA0A6)
$color10 = rgb(9BC247)
$color11 = rgb(CBC547)
$color12 = rgb(FFBAC5)
$color13 = rgb(F5D1A2)
$color14 = rgb(FFDFFC)
$color15 = rgb(F7E6F5)
